[pc_headers]
Accept = "application/json, text/plain, */*"
User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
Accept-Language = "zh-CN,zh;q=0.9"
accept-encoding = "gzip, deflate"
cookie = ""


[app_headers]
User-Agent = "Mozilla/5.0 BiliDroid/5.58.0 (bbcallen@gmail.com)"
Accept-encoding = "gzip"
Buvid = "XZ11bfe2654a9a42d885520a680b3574582eb3"
Display-ID = "146771405-1521008435"
Device-Guid = "2d0bbec5-df49-43c5-8a27-ceba3f74ffd7"
Device-Id = "469a6aaf431b46f8b58a1d4a91d0d95b202004211125026456adffe85ddcb44818"
Accept-Language = "zh-CN"
Accept = "text/html,application/xhtml+xml,*/*;q=0.8"
Connection = "keep-alive"
cookie = ""

[app_params]
actionKey = "appkey"
appkey = "1d8b6e7d45233436"
build = "520001"
device = "android"
mobi_app = "android"
platform = "android"
app_secret = "560c52ccd288fed045859ed18bffd973"


[tv_headers]
Accept = "application/json, text/plain, */*"
User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
Accept-Language = "zh-CN,zh;q=0.9"
accept-encoding = "gzip, deflate"
cookie = ""

[tv_params]
actionKey = "appkey"
appkey = '4409e2ce8ffd12b8'
build = '101800'
device = 'android_tv_yst'
mobi_app = 'android_tv_yst'
platform = 'android_tv_yst'
app_secret = '59b43e04ad6965f34319062b478f83dd'

